In [1]:
import pandas as pd

In [15]:
moviegen_path = "/home/thanhtvt1sc/Downloads/MovieGen-baselines/moviegen_score.tsv"
vggsound_path = "/home/thanhtvt1sc/Downloads/VGGSound-baselines/scores.tsv"

df = pd.read_csv(vggsound_path, sep="\t")
df.rename(columns={"Unnamed: 0": "index"}, inplace=True)
df

       index                path  ib_score  sync_score
0          0  ---g-f_I2yQ_000001  0.188715         1.0
1          1  --U7joUcTCo_000000  0.057703         0.6
2          2  -0BIyqJj9ZU_000030  0.479891         0.4
3          3  -0UuUoXQUoI_000107  0.465876         2.0
4          4  -0Zg_dXR_6I_000013  0.245719         0.6
...      ...                 ...       ...         ...
13677  13677  zyMH_BNFQfA_000032  0.312333         0.0
13678  13678  zywjuHhWmF8_000003  0.277525         0.4
13679  13679  zz0fdUGTHWo_000045  0.070538         1.2
13680  13680  zzFdhaiG_Hk_000095  0.258712         0.6
13681  13681  zzvCPtdNxNo_000068  0.462179         1.2

[13682 rows x 4 columns]

In [16]:
df.sort_values(by="ib_score", inplace=True, ascending=False)
df

       index                path  ib_score  sync_score
10242  10242  gPE8O7DU7ns_000128  0.617780         0.4
10836  10836  jJ6FWcy7B6M_000052  0.617129         0.6
4941    4941  JJMEP5noh34_000110  0.611748         0.2
6178    6178  OPXoyT08GvQ_000017  0.606359         2.0
3557    3557  DQC78JSBJoo_000000  0.601695         0.8
...      ...                 ...       ...         ...
7016    7016  SJUl98voKZo_000003 -0.074283         1.0
12613  12613  skwl9axYSIE_000400 -0.075386         2.0
4345    4345  Gsvye6sfO88_000570 -0.084678         1.2
3237    3237  CB1JIYWrzTs_000033 -0.087922         1.4
2868    2868  Ar0qgvu2BY8_000080 -0.098840         1.2

[13682 rows x 4 columns]

In [17]:
df[:10]

       index                path  ib_score  sync_score
10242  10242  gPE8O7DU7ns_000128  0.617780         0.4
10836  10836  jJ6FWcy7B6M_000052  0.617129         0.6
4941    4941  JJMEP5noh34_000110  0.611748         0.2
6178    6178  OPXoyT08GvQ_000017  0.606359         2.0
3557    3557  DQC78JSBJoo_000000  0.601695         0.8
7922    7922  Wdg90rCeA34_000508  0.596375         0.2
4049    4049  FayXchyGICg_000027  0.587083         0.2
5727    5727  MV1qOqhaLXk_000016  0.586890         2.0
5418    5418  LEFSHa_n9jE_000287  0.585048         0.4
10169  10169  g0RkIkC2meo_000030  0.584231         1.8

In [35]:
df[190:200]

       index                path  ib_score  sync_score
9885    9885  enUxQ7b3PpM_000035  0.529777         0.6
11553  11553  mxczypKrxSc_000013  0.529704         0.6
2917    2917  AzkP4-XZjK0_000080  0.529645         2.0
2119    2119  7W1XzijtwyM_000030  0.529498         1.4
6778    6778  RFjRJmGYrCg_000572  0.529440         1.6
6578    6578  QO00gXws7ak_000030  0.529252         0.2
1129    1129  3NvKtRbbOYU_000310  0.529234         2.0
13023  13023  vcZ3gN9ZRcA_000100  0.529226         2.0
1546    1546  5ANOPKg4-dg_000012  0.529189         2.0
11498  11498  mi7kgfvwTAw_000005  0.529168         0.4